# R34SEMModel.R
# Date: Feb 13, 2018 8:03:12 AM 2018
#
# Author: M. Joseph Meyer
###############################################################################
#
# Revision History
# Feb 13, 2018 8:03:12 AM 2018: R34SEMModel.R was created.
#
#
################################################################################
### NOTES ON REPORTING RESULTS
#diffLL = LogLikliehood difference between the two models, bigger = bigger diff between marbles
#diffdf = difference 2 parameters (because both slope diff and intercept diff are being compared, if just slope or just intercept, diffLL = 1)
#AIC = criterion for each model, comparing models, 
#Output:1=model with the MOST parameters, 2=model with FEWER parameters, 1 should be to the left of 2 in order, and it's testing if FEWER parameter model is BETTER than MAX parameter mdoel

install.packages('OpenMx')
library(OpenMx)
require(OpenMx)

dir.name <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(dir.name)
dir()

############ 
############ 
############ 
############ DV=Recognition Rating Negative Score

RRNeg_modelData <- read.csv("R34_FinalData_New_v02.csv")

RRNeg_modelData$RRNegative_PRE <- RRNeg_modelData$RR_negative_ns_score_PRE

RRNeg_modelData[] <- lapply(RRNeg_modelData, as.numeric)

# This model specification was automatically generated by Onyx, i.e. ALL PATHS ARE DIFFERENT
manifests<-c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL")
latents<-c("Intercept","Slope")

##Model where Ha = all 6 groups differ
RRNeg_modelAllDiff <- mxModel("RRNeg_modelAllDiff", 
		type="RAM",
		manifestVars = manifests,
		latentVars = latents,
		mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
		mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
		#mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
		mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
		mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
		mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
		mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
		mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
		mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
		mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
		mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
		mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
		mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
		mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
		#mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
		mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
		mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
		mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
		mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
		mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
		mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
		mxData(RRNeg_modelData, type = "raw")
);

resultRRNeg_modelAllDiff <- mxRun(RRNeg_modelAllDiff)
summary(resultRRNeg_modelAllDiff) #summary table

###### POS TRAINING GROUPS VS. NO-TRAIN CONTROL GROUPS #######

#PosAnx = NoTrainNeut 
modPosAnxSameNoneNeut<-mxModel(RRNeg_modelAllDiff,
                   mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                          value=c(0.0,0.0), arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ))
resultmodPosAnxSameNoneNeut <- mxRun(modPosAnxSameNoneNeut)
mxCompare(resultRRNeg_modelAllDiff, resultmodPosAnxSameNoneNeut)

#### PosAnx = NoTrainAnx
modelPosAnxNoneAnxSame <- mxModel("R34_RRNeg_ModelPosAnxNoneAnxSame", 
                                  type="RAM",
                                  manifestVars = manifests,
                                  latentVars = latents,
                                  mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                  mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                  #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                  mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                  mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                                  mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                  mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                  mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                  mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                                  mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                  mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                  mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                  mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                  mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                  #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                  mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                  mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                  mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                  mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                  mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                  mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                  mxData(RRNeg_modelData, type = "raw")
);
resultmodelPosAnxNoneAnxSame <- mxRun(modelPosAnxNoneAnxSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodelPosAnxNoneAnxSame) #PosAnx=NoTrainAnx same is not different from ModelAllDifferent, i.e. they do not differ!

#PosNeut = NoTrainNeut
modPosNeutSameNoneNeut <-mxModel(RRNeg_modelAllDiff,
                                 mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                                        value=c(0.0,0.0), arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ))
resultmodPosNeutSameNoneNeut <- mxRun(modPosNeutSameNoneNeut)
mxCompare(resultRRNeg_modelAllDiff,resultmodPosNeutSameNoneNeut)

#### PosNeut = NoTrainAnx
modelPosNeutNoneAnxSame <- mxModel("R34_RRNeg_ModelPosNeutNoneAnxSame", 
                                   type="RAM",
                                   manifestVars = manifests,
                                   latentVars = latents,
                                   mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                   mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                   #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                   mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                                   mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                   mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                                   mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                   mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                                   mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                   mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                   mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                   mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                   mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                   #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                   mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                   mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                   mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                   mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                   mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                   mxData(RRNeg_modelData, type = "raw")
);
resultmodelPosNeutNoneAnxSame <- mxRun(modelPosNeutNoneAnxSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodelPosNeutNoneAnxSame) #PosAnx=NoTrainAnx same is not different from ModelAllDifferent, i.e. they do not differ!


###### 5050 TRAINING GROUPS VS. NO-TRAIN CONTROL GROUPS ######

#5050Anx = NoTrainAnx
mod5050AnxSameNoneNeut <-mxModel(RRNeg_modelAllDiff,
                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                          value=c(0.0,0.0), arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ))
resultmod5050AnxSameNoneNeut<- mxRun(mod5050AnxSameNoneNeut)
mxCompare(resultRRNeg_modelAllDiff,resultmod5050AnxSameNoneNeut)

#### 5050Anx = NoTrainAnx
model5050AnxNoneAnxSame <- mxModel("model5050AnxNoneAnxSame", 
                                   type="RAM",
                                   manifestVars = manifests,
                                   latentVars = latents,
                                   mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                   mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                   #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                   mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope", "SAME__Intercept") ),
                                   mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                   mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                                   mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                   mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Slope__Intercept") ),
                                   mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                   mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                   mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                   mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                   mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                   #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                   mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                   mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                   mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                   mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                   mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                   mxData(RRNeg_modelData, type = "raw")
);
resultmodel5050AnxNoneAnxSame <- mxRun(model5050AnxNoneAnxSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodel5050AnxNoneAnxSame) #PosAnx=NoTrainAnx same is not different from ModelAllDifferent, i.e. they do not differ!

#### 5050Neut = NoTrainAnx
model5050NeutNoneAnxSame <- mxModel("R34_RRNeg_model5050NeutNoneAnxSame", 
                                    type="RAM",
                                    manifestVars = manifests,
                                    latentVars = latents,
                                    mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                    mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                    #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                    mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                    mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope", "FIFTY_FIFTYANXIETY__Intercept") ),
                                    mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                    mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                                    mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                    mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                    mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                    mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                    mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                    mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                    mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                    #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                    mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                    mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                    mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                    mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                    mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                    mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                    mxData(RRNeg_modelData, type = "raw")
);
resultmodel5050NeutNoneAnxSame <- mxRun(model5050NeutNoneAnxSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodel5050NeutNoneAnxSame) 

#5050Neut = NoneNeut 
mod5050NeutSameNoneNeut<-mxModel(RRNeg_modelAllDiff,
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                                                value=c(0.0,0.0), arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ))
resultmod5050NeutSameNoneNeut <- mxRun(mod5050NeutSameNoneNeut)
mxCompare(resultRRNeg_modelAllDiff,resultmod5050NeutSameNoneNeut)

###### PART B ######: ACTIVE GROUPS VS. EACH OTHER

#### PosAnx = 5050Anx
modelPosAnx50AnxSame <- mxModel("R34_RRNeg_modelPosAnx50AnxSame", 
                                type="RAM",
                                manifestVars = manifests,
                                latentVars = latents,
                                mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                                mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                mxData(RRNeg_modelData, type = "raw")
);
resultmodelPosAnx50AnxSame <- mxRun(modelPosAnx50AnxSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodelPosAnx50AnxSame) #PosAnx=5050Anx same is different from ModelAllDifferent, i.e. they differ!!

####PosNeut = 5050Anx
model5050AnxPosNeutSame <- mxModel("model5050AnxPosNeutSame", 
                                   type="RAM",
                                   manifestVars = manifests,
                                   latentVars = latents,
                                   mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                   mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                   #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                   mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope", "SAME__Intercept") ),
                                   mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                   mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                                   mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                   mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Slope__Intercept") ),
                                   mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                   mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                   mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                   mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                   mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                   #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                   mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                   mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                   mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                   mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                   mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                   mxData(RRNeg_modelData, type = "raw")
);
resultmodel5050AnxPosNeutSame <- mxRun(model5050AnxPosNeutSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodel5050AnxPosNeutSame) #PosAnx=NoTrainAnx same is not different from ModelAllDifferent, i.e. they do not differ!

#### PosNeut = 5050Neut
modelPosNeut5050NeutSame <- mxModel("modelPosNeut5050NeutSame", 
                                   type="RAM",
                                   manifestVars = manifests,
                                   latentVars = latents,
                                   mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                   mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                   #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                   mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope", "FIFTY_FIFTYANXIETY__Intercept") ),
                                   mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                   mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                                   mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                   mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                   mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                   mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                   mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                   mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                   mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                   #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                   mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                   mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                   mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                   mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                   mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                   mxData(RRNeg_modelData, type = "raw")
);
resultmodelPosNeut5050NeutSame<- mxRun(modelPosNeut5050NeutSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodelPosNeut5050NeutSame) #PosAnx=NoTrainAnx same is not different from ModelAllDifferent, i.e. they do not differ!

#### PosAnx = 5050Neut
modelPosAnx5050NeutSame <- mxModel("modelPosAnx5050NeutSame", 
                                    type="RAM",
                                    manifestVars = manifests,
                                    latentVars = latents,
                                    mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                    mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                    #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                    mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                    mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope", "FIFTY_FIFTYANXIETY__Intercept") ),
                                    mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                    mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                    mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                    mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                    mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                    mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                    mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                    mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                    mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                    #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                    mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                    mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                    mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                    mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                    mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                    mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                    mxData(RRNeg_modelData, type = "raw")
);
resultmodelPosAnx5050NeutSame<- mxRun(modelPosAnx5050NeutSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodelPosAnx5050NeutSame) 

#### PosAnx = PosNeut 
modelPosAnxPosNeutSame <- mxModel("R34_RRNeg_modelPosAnxPosNeutSame", 
                                  type="RAM",
                                  manifestVars = manifests,
                                  latentVars = latents,
                                  mxPath(from="Intercept",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRNegative_PRE","Intercept__RRNegative_SESSION3","Intercept__RRNegative_SESSION6") ),
                                  mxPath(from="Slope",to=c("RRNegative_PRE","RRNegative_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRNegative_PRE","Slope__RRNegative_SESSION3") ),
                                  #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                  mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                  mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                                  mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                  mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                  mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                  mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                                  mxPath(from="RRNegative_PRE",to=c("RRNegative_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_PRE") ),
                                  mxPath(from="RRNegative_SESSION3",to=c("RRNegative_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION3") ),
                                  mxPath(from="RRNegative_SESSION6",to=c("RRNegative_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRNegative_SESSION6") ),
                                  mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                  mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                  #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                  mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                  mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                  mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                  mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                  mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                  mxPath(from="one",to=c("RRNegative_PRE","RRNegative_SESSION3","RRNegative_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                  mxData(RRNeg_modelData, type = "raw")
);
resultmodelPosAnxPosNeutSame <- mxRun(modelPosAnxPosNeutSame)
mxCompare(resultRRNeg_modelAllDiff, resultmodelPosAnxPosNeutSame) #PosAnxvsPosNeut diff is not better than ModelAllDifferent. 
