# R34SEMModel.R
# Date: Feb 13, 2018 8:03:12 AM 2018
#
# Author: M. Joseph Meyer
###############################################################################
#
# Revision History
# Feb 13, 2018 8:03:12 AM 2018: R34SEMModel.R was created.
#
#
################################################################################
### NOTES ON REPORTING RESULTS
#diffLL = LogLikliehood difference between the two models, bigger = bigger diff between marbles
#diffdf = difference 2 parameters (because both slope diff and intercept diff are being compared, if just slope or just intercept, diffLL = 1)
#AIC = criterion for each model, comparing models, 
#Output:1=model with the MOST parameters, 2=model with FEWER parameters, 1 should be to the left of 2 in order, and it's testing if FEWER parameter model is BETTER than MAX parameter mdoel

install.packages('OpenMx')
library(OpenMx)

dir.name <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(dir.name)
dir()

OASIS_modelData <- read.csv("R34_FinalData_New.csv")
OASIS_modelData[] <- lapply(OASIS_modelData, as.numeric)

# This model specification was automatically generated by Onyx, i.e. ALL PATHS ARE DIFFERENT
manifests<-c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL")
latents<-c("Intercept","Slope")

##Model where Ha = all 6 groups differ
modelAllDiff <- mxModel("OASIS_modelData", 
		type="RAM",
		manifestVars = manifests,
		latentVars = latents,
		mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
		mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
		#mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
		mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
		mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
		mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
		mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
		mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
		mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
		mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
		mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
		mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
		mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
		mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
		mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
		mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
		mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
		mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
		#mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
		mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
		mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
		mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
		mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
		mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
		mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
		mxData(OASIS_modelData, type = "raw")
);

resultModelAllDiff <- mxRun(modelAllDiff)
summary(resultModelAllDiff) #summary table

###### PART A ######: ACTIVE GROUPS VS. NO TRAINING CONTROL GROUPS

#### PosAnx = NoTrainNeut
modPosAnxSameNoneNeut<-mxModel(modelAllDiff,
                   mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                          value=c(0.0,0.0), arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ))
resultmodPosAnxSameNoneNeut <- mxRun(modPosAnxSameNoneNeut)
mxCompare(resultModelAllDiff,resultmodPosAnxSameNoneNeut)

#### PosNeut = NoTrainNeut
modPosNeutSameNoneNeut <-mxModel(modelAllDiff,
                    mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                           value=c(0.0,0.0), arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ))
resultmodPosNeutSameNoneNeut <- mxRun(modPosNeutSameNoneNeut)
mxCompare(resultModelAllDiff,resultmodPosNeutSameNoneNeut)

#### PosAnx = NoTrainAnx 
modelPosAnxNoneAnx <- mxModel("modelPosAnxNoneAnx", 
                              type="RAM",
                              manifestVars = manifests,
                              latentVars = latents,
                              mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
                              mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
                              #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                              mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                              mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                              mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
                              mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
                              mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
                              mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
                              mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
                              mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
                              mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
                              mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                              mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                              #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                              mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                              mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                              mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                              mxData(OASIS_modelData, type = "raw")
);
resultmodelPosAnxNoneAnx <- mxRun(modelPosAnxNoneAnx)
mxCompare(resultModelAllDiff, resultmodelPosAnxNoneAnx)  

#### PosNeut = NoTrainAnx 
modelPosNeutNoneAnx <- mxModel("modelPosNeutNoneAnx", 
                               type="RAM",
                               manifestVars = manifests,
                               latentVars = latents,
                               mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
                               mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
                               #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                               mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                               mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                               mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                               mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                               mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                               mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                               mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
                               mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
                               mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
                               mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
                               mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
                               mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
                               mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
                               mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                               mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                               #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                               mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                               mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                               mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                               mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                               mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                               mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                               mxData(OASIS_modelData, type = "raw")
);
resultmodelPosNeutNoneAnx <- mxRun(modelPosNeutNoneAnx)
mxCompare(resultModelAllDiff, resultmodelPosNeutNoneAnx)  

#### 5050Anx = NoTrainNeut 
mod5050AnxSameNoneNeut <-mxModel(modelAllDiff,
                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                          value=c(0.0,0.0), arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ))
resultmod5050AnxSameNoneNeut<- mxRun(mod5050AnxSameNoneNeut)
mxCompare(resultModelAllDiff,resultmod5050AnxSameNoneNeut)

#### 5050Neut = NoTrainNeut 
mod5050NeutSameNoneNeut<-mxModel(modelAllDiff,
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                                                value=c(0.0,0.0), arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ))
resultmod5050NeutSameNoneNeut <- mxRun(mod5050NeutSameNoneNeut)
mxCompare(resultModelAllDiff,resultmod5050NeutSameNoneNeut)

#### 5050Anx = NoTrainAnx 
model5050AnxNoneAnx <- mxModel("model5050AnxNoneAnx", 
                              type="RAM",
                              manifestVars = manifests,
                              latentVars = latents,
                              mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
                              mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
                              #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                              mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                              mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
                              mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
                              mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
                              mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
                              mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
                              mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
                              mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
                              mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                              mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                              #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                              mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                              mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                              mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                              mxData(OASIS_modelData, type = "raw")
);
resultmodel5050AnxNoneAnx <- mxRun(model5050AnxNoneAnx)
mxCompare(resultModelAllDiff, resultmodel5050AnxNoneAnx)  


#### 5050Neut = NoneAnx 
model5050NeutNoneAnx <- mxModel("model5050NeutNoneAnx", 
                               type="RAM",
                               manifestVars = manifests,
                               latentVars = latents,
                               mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
                               mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
                               #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                               mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                               mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                               mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                               mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                               mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                               mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                               mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
                               mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
                               mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
                               mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
                               mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
                               mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
                               mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
                               mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                               mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                               #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                               mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                               mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                               mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                               mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                               mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                               mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                               mxData(OASIS_modelData, type = "raw")
);
resultmodel5050NeutNoneAnx <- mxRun(model5050NeutNoneAnx)
mxCompare(resultModelAllDiff, resultmodel5050NeutNoneAnx)  

###### PART B ######: ACTIVE GROUPS VS. EACH OTHER

#### PosAnx = 5050Anx 
modelPosAnx5050Anx <- mxModel("modelPosAnx5050Anx", 
                              type="RAM",
                              manifestVars = manifests,
                              latentVars = latents,
                              mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
                              mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
                              #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                              mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                              mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                              mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
                              mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
                              mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
                              mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
                              mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
                              mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
                              mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
                              mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                              mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                              #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                              mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                              mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                              mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                              mxData(OASIS_modelData, type = "raw")
);
resultmodelPosAnx5050Anx <- mxRun(modelPosAnx5050Anx)
mxCompare(resultModelAllDiff, resultmodelPosAnx5050Anx)  

#### PosAnx = 5050Neut 
modelPosAnx5050Neut <- mxModel("modelPosAnx5050Neut", 
                              type="RAM",
                              manifestVars = manifests,
                              latentVars = latents,
                              mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
                              mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
                              #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                              mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                              mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                              mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
                              mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
                              mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
                              mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
                              mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
                              mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
                              mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
                              mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                              mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                              #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                              mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                              mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                              mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                              mxData(OASIS_modelData, type = "raw")
);
resultmodelPosAnx5050Neut <- mxRun(modelPosAnx5050Neut)
mxCompare(resultModelAllDiff, resultmodelPosAnx5050Neut)  

#### PosNeut = 5050Anx 
modelPosNeut5050Anx <- mxModel("modelPosNeut5050Anx", 
                              type="RAM",
                              manifestVars = manifests,
                              latentVars = latents,
                              mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
                              mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
                              #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                              mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                              mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                              mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
                              mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
                              mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
                              mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
                              mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
                              mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
                              mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
                              mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                              mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                              #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                              mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                              mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                              mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                              mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                              mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                              mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                              mxData(OASIS_modelData, type = "raw")
);
resultmodelPosNeut5050Anx <- mxRun(modelPosNeut5050Anx)
mxCompare(resultModelAllDiff, resultmodelPosNeut5050Anx)  

#### PosAnx = 5050Neut 
modelPosNeut5050Neut <- mxModel("modelPosNeut5050Neut", 
                               type="RAM",
                               manifestVars = manifests,
                               latentVars = latents,
                               mxPath(from="Intercept",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6"), free=c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("Intercept__OASISScore_PRE","Intercept__OASISScore_SESSION1","Intercept__OASISScore_SESSION2","Intercept__OASISScore_SESSION3","Intercept__OASISScore_SESSION4","Intercept__OASISScore_SESSION5","Intercept__OASISScore_SESSION6") ),
                               mxPath(from="Slope",to=c("OASISScore_PRE","OASISScore_SESSION6"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__OASISScore_PRE","Slope__OASISScore_SESSION6") ),
                               #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                               mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                               mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                               mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                               mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                               mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                               mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                               mxPath(from="OASISScore_PRE",to=c("OASISScore_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_PRE") ),
                               mxPath(from="OASISScore_SESSION1",to=c("OASISScore_SESSION1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION1") ),
                               mxPath(from="OASISScore_SESSION2",to=c("OASISScore_SESSION2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION2") ),
                               mxPath(from="OASISScore_SESSION3",to=c("OASISScore_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION3") ),
                               mxPath(from="OASISScore_SESSION4",to=c("OASISScore_SESSION4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION4") ),
                               mxPath(from="OASISScore_SESSION5",to=c("OASISScore_SESSION5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION5") ),
                               mxPath(from="OASISScore_SESSION6",to=c("OASISScore_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_OASISScore_SESSION6") ),
                               mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                               mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                               #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                               mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                               mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                               mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                               mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                               mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                               mxPath(from="one",to=c("OASISScore_PRE","OASISScore_SESSION1","OASISScore_SESSION2","OASISScore_SESSION3","OASISScore_SESSION4","OASISScore_SESSION5","OASISScore_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                               mxData(OASIS_modelData, type = "raw")
);
resultmodelPosNeut5050Neut <- mxRun(modelPosNeut5050Neut)
mxCompare(resultModelAllDiff, resultmodelPosNeut5050Neut)  

