# R34SEMModel.R
# Date: Feb 13, 2018 8:03:12 AM 2018
#
# Author: M. Joseph Meyer
###############################################################################
#
# Revision History
# Feb 13, 2018 8:03:12 AM 2018: R34SEMModel.R was created.
#
#
################################################################################
### NOTES ON REPORTING RESULTS
#diffLL = LogLikliehood difference between the two models, bigger = bigger diff between marbles
#diffdf = difference 2 parameters (because both slope diff and intercept diff are being compared, if just slope or just intercept, diffLL = 1)
#AIC = criterion for each model, comparing models, 
#Output:1=model with the MOST parameters, 2=model with FEWER parameters, 1 should be to the left of 2 in order, and it's testing if FEWER parameter model is BETTER than MAX parameter mdoel

install.packages('OpenMx')
library(OpenMx)

dir.name <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(dir.name)
dir()

RRPos_modelData <- read.csv("R34_FinalData_New.csv")
RRPos_modelData[] <- lapply(RRPos_modelData, as.numeric)

# This model specification was automatically generated by Onyx, i.e. ALL PATHS ARE DIFFERENT
manifests<-c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL")
latents<-c("Intercept","Slope")

##Model where Ha = all 6 groups differ
RRPos_modelAllDiff <- mxModel("RRPos_modelAllDiff", 
		type="RAM",
		manifestVars = manifests,
		latentVars = latents,
		mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
		mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
		#mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
		mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
		mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
		mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
		mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
		mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
		mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
		mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
		mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
		mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
		mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
		mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
		#mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
		mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
		mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
		mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
		mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
		mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
		mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
		mxData(RRPos_modelData, type = "raw")
);

resulRRPos_modelAllDiff <- mxRun(RRPos_modelAllDiff)
summary(resulRRPos_modelAllDiff) #summary table

###### PART A ######: ACTIVE GROUPS VS. NO TRAINING CONTROL GROUPS

#### PosAnx = NoTrainNeut
RRPos_modPosAnxSameNoneNeut<-mxModel(RRPos_modelAllDiff,
                   mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                          value=c(0.0,0.0), arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ))
resultRRPos_modPosAnxSameNoneNeut <- mxRun(RRPos_modPosAnxSameNoneNeut)
mxCompare(resulRRPos_modelAllDiff,resultRRPos_modPosAnxSameNoneNeut)

#### PosAnx = NoTrainAnx
RRPos_modelPosAnxNoneAnxSame <- mxModel("RRPos_modelPosAnxNoneAnxSame", 
                                        type="RAM",
                                        manifestVars = manifests,
                                        latentVars = latents,
                                        mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
                                        mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
                                        #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                        mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                        mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                                        mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                        mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                        mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                        mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                                        mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
                                        mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
                                        mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
                                        mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                        mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                        #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                        mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                        mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                        mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                        mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                        mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                        mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                        mxData(RRPos_modelData, type = "raw")
);
resultRRPos_modelPosAnxNoneAnxSame <- mxRun(RRPos_modelPosAnxNoneAnxSame)
mxCompare(resulRRPos_modelAllDiff, resultRRPos_modelPosAnxNoneAnxSame) #PosAnx=NoTrainAnx same is not different from ModelAllDifferent, i.e. they do not differ!

#### PosNeut = NoTrainNeut 
RRPos_modPosNeutSameNoneNeut <-mxModel(RRPos_modelAllDiff,
                    mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                           value=c(0.0,0.0), arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ))
resultRRPos_modPosNeutSameNoneNeut <- mxRun(RRPos_modPosNeutSameNoneNeut)
mxCompare(resulRRPos_modelAllDiff,resultRRPos_modPosNeutSameNoneNeut)

#### PosNeut = NoTrainAnx
RRPos_modelPosNeutNoneAnxSame <- mxModel("RRPos_modelPosNeutNoneAnxSame", 
                                         type="RAM",
                                         manifestVars = manifests,
                                         latentVars = latents,
                                         mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
                                         mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
                                         #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                         mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                         mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                                         mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                         mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY_Slope","POSITIVEANXIETY__Intercept") ),
                                         mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                                         mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
                                         mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
                                         mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
                                         mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                         mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                         #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                         mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                         mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                         mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                         mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                         mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                         mxData(RRPos_modelData, type = "raw")
);
resultRRPos_modelPosNeutNoneAnxSame <- mxRun(RRPos_modelPosNeutNoneAnxSame)
mxCompare(resulRRPos_modelAllDiff, resultRRPos_modelPosNeutNoneAnxSame) #PosAnx=NoTrainAnx same is not different from ModelAllDifferent, i.e. they do not differ!

#### 5050Anx = NoTrainAnx
RRPos_model5050AnxNoneAnxSame <- mxModel("RRPos_model5050AnxNoneAnxSame", 
                                         type="RAM",
                                         manifestVars = manifests,
                                         latentVars = latents,
                                         mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
                                         mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
                                         #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                         mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                         mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope", "SAME__Intercept") ),
                                         mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                         mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                                         mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Slope__Intercept") ),
                                         mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
                                         mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
                                         mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
                                         mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                         mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                         #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                         mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                         mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                         mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                         mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                         mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                         mxData(RRPos_modelData, type = "raw")
);
resultRRPos_model5050AnxNoneAnxSame <- mxRun(RRPos_model5050AnxNoneAnxSame)
mxCompare(resulRRPos_modelAllDiff, resultRRPos_model5050AnxNoneAnxSame) #PosAnx=NoTrainAnx same is not different from ModelAllDifferent, i.e. they do not differ!

#### 5050Anx = NoTrainNeut 
RRPos_mod5050AnxSameNoneNeut <-mxModel(RRPos_modelAllDiff,
                   mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                          value=c(0.0,0.0), arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ))
resultRRPos_mod5050AnxSameNoneNeut<- mxRun(RRPos_mod5050AnxSameNoneNeut)
mxCompare(resulRRPos_modelAllDiff,resultRRPos_mod5050AnxSameNoneNeut)

#### 5050Neut = NoTrainNeut 
RRPos_mod5050NeutSameNoneNeut <-mxModel(RRPos_modelAllDiff,
                                       mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(FALSE,FALSE), 
                                              value=c(0.0,0.0), arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ))
resultRRPos_mod5050NeutSameNoneNeut<- mxRun(RRPos_mod5050NeutSameNoneNeut)
mxCompare(resulRRPos_modelAllDiff,resultRRPos_mod5050NeutSameNoneNeut)

#### 5050Neut = NoneAnx
RRPos_model5050NeutNoneAnxSame <- mxModel("RRPos_model5050NeutNoneAnxSame", 
                                          type="RAM",
                                          manifestVars = manifests,
                                          latentVars = latents,
                                          mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
                                          mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
                                          #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                          mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                          mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope", "FIFTY_FIFTYANXIETY__Intercept") ),
                                          mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                          mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY__Slope","POSITIVEANXIETY__Intercept") ),
                                          mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                          mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                          mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
                                          mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
                                          mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
                                          mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                          mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                          #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                          mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                          mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                          mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                          mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                          mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                          mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                          mxData(RRPos_modelData, type = "raw")
);
resultRRPos_model5050NeutNoneAnxSame <- mxRun(RRPos_model5050NeutNoneAnxSame)
mxCompare(resulRRPos_modelAllDiff, resultRRPos_model5050NeutNoneAnxSame) 

###### PART B ######: ACTIVE GROUPS VS. EACH OTHER

#### PosAnx = 5050Anx
RRPos_modelPosAnx50AnxSame <- mxModel("RRPos_modelPosAnx50AnxSame", 
                                      type="RAM",
                                      manifestVars = manifests,
                                      latentVars = latents,
                                      mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
                                      mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
                                      #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                      mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                      mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                      mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                      mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                      mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                      mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                                      mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
                                      mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
                                      mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
                                      mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                      mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                      #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                      mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                      mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                      mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                      mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                      mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                      mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                      mxData(RRPos_modelData, type = "raw")
);
resultRRPos_modelPosAnx50AnxSame <- mxRun(RRPos_modelPosAnx50AnxSame)
mxCompare(resulRRPos_modelAllDiff, resultRRPos_modelPosAnx50AnxSame) #PosAnx=5050Anx same is different from ModelAllDifferent, i.e. they differ!!

#### PosAnx = 5050Neut
RRPos_modelPosAnx50NeutSame <- mxModel("RRPos_modelPosAnx50NeutSame", 
                                       type="RAM",
                                       manifestVars = manifests,
                                       latentVars = latents,
                                       mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
                                       mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
                                       #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                       mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                       mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                                       mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                       mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                       mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVENEUTRAL__Slope","POSITIVENEUTRAL__Intercept") ),
                                       mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                       mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
                                       mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
                                       mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
                                       mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                       mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                       #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                       mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                       mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                       mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                       mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                       mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                       mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                       mxData(RRPos_modelData, type = "raw")
);
resultRRPos_modelPosAnx50NeutSame <- mxRun(RRPos_modelPosAnx50NeutSame)
mxCompare(resulRRPos_modelAllDiff, resultRRPos_modelPosAnx50NeutSame) 

#### PosNeut = 5050Anx
RRPos_modelPosNeut5050AnxSame <- mxModel("RRPos_modelPosNeut5050AnxSame", 
                                         type="RAM",
                                         manifestVars = manifests,
                                         latentVars = latents,
                                         mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
                                         mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
                                         #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                         mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                         mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                         mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                         mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY_Slope","POSITIVEANXIETY__Intercept") ),
                                         mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYNEUTRAL__Slope","FIFTY_FIFTYNEUTRAL__Intercept") ),
                                         mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
                                         mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
                                         mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
                                         mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                         mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                         #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                         mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                         mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                         mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                         mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                         mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                         mxData(RRPos_modelData, type = "raw")
);
resultRRPos_modelPosNeut5050AnxSame <- mxRun(RRPos_modelPosNeut5050AnxSame)
mxCompare(resulRRPos_modelAllDiff, resultRRPos_modelPosNeut5050AnxSame) 

#### PosNeut = 5050Neut
RRPos_modelPosNeut5050NeutSame <- mxModel("RRPos_modelPosNeut5050NeutSame", 
                                         type="RAM",
                                         manifestVars = manifests,
                                         latentVars = latents,
                                         mxPath(from="Intercept",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("Intercept__RRPositive_PRE","Intercept__RRPositive_SESSION3","Intercept__RRPositive_SESSION6") ),
                                         mxPath(from="Slope",to=c("RRPositive_PRE","RRPositive_SESSION3"), free=c(FALSE,FALSE), value=c(-2.0,-1.0) , arrows=1, label=c("Slope__RRPositive_PRE","Slope__RRPositive_SESSION3") ),
                                         #mxPath(from="Dropout",to=c("Intercept"), free=c(TRUE), value=c(0.8) , arrows=1, label=c("Dropout__Intercept") ),
                                         mxPath(from="one",to=c("Intercept","Slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__Intercept","const__Slope") ),
                                         mxPath(from="FIFTY_FIFTYANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("FIFTY_FIFTYANXIETY__Slope","FIFTY_FIFTYANXIETY__Intercept") ),
                                         mxPath(from="NONEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("NONEANXIETY__Slope","NONEANXIETY__Intercept") ),
                                         mxPath(from="POSITIVEANXIETY",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("POSITIVEANXIETY_Slope","POSITIVEANXIETY__Intercept") ),
                                         mxPath(from="POSITIVENEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("Slope","Intercept"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("SAME__Slope","SAME__Intercept") ),
                                         mxPath(from="RRPositive_PRE",to=c("RRPositive_PRE"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_PRE") ),
                                         mxPath(from="RRPositive_SESSION3",to=c("RRPositive_SESSION3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION3") ),
                                         mxPath(from="RRPositive_SESSION6",to=c("RRPositive_SESSION6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_RRPositive_SESSION6") ),
                                         mxPath(from="Intercept",to=c("Intercept"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Intercept") ),
                                         mxPath(from="Slope",to=c("Slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Slope") ),
                                         #mxPath(from="Dropout",to=c("Dropout"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_Dropout") ),
                                         mxPath(from="FIFTY_FIFTYANXIETY",to=c("FIFTY_FIFTYANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYANXIETY") ),
                                         mxPath(from="NONEANXIETY",to=c("NONEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_NONEANXIETY") ),
                                         mxPath(from="POSITIVEANXIETY",to=c("POSITIVEANXIETY"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVEANXIETY") ),
                                         mxPath(from="POSITIVENEUTRAL",to=c("POSITIVENEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_POSITIVENEUTRAL") ),
                                         mxPath(from="FIFTY_FIFTYNEUTRAL",to=c("FIFTY_FIFTYNEUTRAL"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_FIFTY_FIFTYNEUTRAL") ),
                                         mxPath(from="one",to=c("RRPositive_PRE","RRPositive_SESSION3","RRPositive_SESSION6","FIFTY_FIFTYANXIETY","NONEANXIETY","POSITIVEANXIETY","POSITIVENEUTRAL","FIFTY_FIFTYNEUTRAL"), free=F, value=0, arrows=1),
                                         mxData(RRPos_modelData, type = "raw")
);
resultRRPos_modelPosNeut5050NeutSame <- mxRun(RRPos_modelPosNeut5050NeutSame)
mxCompare(resulRRPos_modelAllDiff, resultRRPos_modelPosNeut5050NeutSame) 

